version: 2.1

workflows:
  Release Pipeline:
    jobs:
      - Build:
          filters:
            branches:
              only: development
      - Run Backend Automation Test Cases:
          requires:
            - Build
      - Deploy to Test Environment:
          requires:
            - Run Backend Automation Test Cases
      - QA Team Approval:
          type: approval
          requires:
            - Deploy to Test Environment
      - Deploy to Staging Environment:
          requires:
            - QA Team Approval
      - Product Team Approval:
          type: approval
          requires:
            - Deploy to Staging Environment
      - Deploy to Production Environment:
          requires:
            - Product Team Approval

  Development Pipeline:
    jobs:
      - Build:
          filters:
            branches:
              ignore: [main,development]
      - Run Backend Automation Test Cases:
          requires:
            - Build
      - Deploy to Backend Development Environment:
          requires:
            - Run Backend Automation Test Cases

jobs:
  Build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      #- run:
      #    name: "Failing a build"
      #    command: "time.sleep"
      - run:
          name: "Build Docker and push docker"
          command: "echo Building docker out of $CIRCLE_PROJECT_REPONAME on Branch $CIRCLE_BRANCH"
      - run:
          name: "Creating and uploading helm chart"
          command: "echo creating anf uploading helm chart"

  Run Backend Automation Test Cases:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # - run:
      #    name: "Failing a build"
      #    command: "time.sleep"
      - run:
          name: "Deploy to obelix-automation.stv.amagi.tv"
          command: "echo deploying the helm into automation environment"
      - run:
          name: "Pull the test cases"
          command: "echo successfully ran the test cases"
      - run:
          name: "Validating the test cases"
          command: "echo successfully validated the test cases"
      - run:
          name: "Echo param"
          command: "echo export SLACK_PARAM_MENTIONS='<@$SLACK_USER_ID>' >> $BASH_ENV"

  Deploy to Backend Development Environment:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
    #  - run:
    #     name: "Failing a build"
    #     command: "time.sleep"
      - run:
          name: "Deploy to obelix-automation.stv.amagi.tv"
          command: "echo deploying the helm into automation environment"

  Deploy to Test Environment:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Deploy to obelix.test.stv.amagi.tv"
          command: "echo deploying the helm into test environment"

  Deploy to Staging Environment:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Deploy to obelix.staging.stv.amagi.tv"
          command: "echo deploying the helm into staging environment"

  Deploy to Production Environment:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Creating release tag based on central repo"
          command: "echo created release tag v0.0.1"
      - run:
          name: "Deploy to amaginow.tv"
          command: "echo deploying the helm into production environment"
      - run:
          name: "Update documentation with new release note"
          command: "echo updated documentation with new release notes"

