#!/bin/sh

rt=$(git rev-parse --abbrev-ref HEAD)
yy="([0-9]{5})(-)([a-z]*)"
echo "$rt"
if ! [[ $rt =~ $yy ]]; then
  echo "Your commit was rejected due to branching name $rt"
  echo "Please rename your branch with $yy syntax"
  exit 1
  else
    echo "OK"
fi
~     
